### ISSUE TITLE
Failure when creating servicegroups

### ISSUE THREAD

**Issue by tacchino** [sous-chefs/nagios#347] opened 2015-03-27 12:46 UTC
When a servicegroup data bag item is defined the cookbook will fail when trying to call Servicegroup.create, it is not defined.

```
================================================================================
Error executing action `update` on resource 'nagios_resourcelist_items[update]'
================================================================================


NoMethodError
-------------
undefined method `create' for Nagios::Servicegroup:Class


Cookbook Trace:
---------------
/var/chef/cache/cookbooks/nagios/providers/resourcelist_items.rb:60:in `update_object'
/var/chef/cache/cookbooks/nagios/providers/resourcelist_items.rb:46:in `block (2 levels) in class_from_file'
/var/chef/cache/cookbooks/nagios/providers/resourcelist_items.rb:21:in `block in class_from_file'


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/nagios/recipes/default.rb

169: nagios_resourcelist_items 'update'
170:



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/nagios/recipes/default.rb:169:in `from_file'

nagios_resourcelist_items("update") do
  action :update
  retries 0
  retry_delay 2
  cookbook_name "nagios"
  recipe_name "default"
end
```

**Comment by sbotman** [comment] 2015-03-27 13:19
Thanks for reporting this, can you please check if https://github.com/tas50/nagios/pull/348 fixes your issue. 

Cheers Sander

**Comment by tacchino** [comment] 2015-03-27 14:46
Yep, that does get me past the failure but it looks like that branch doesn't have #345 in it?

**Comment by sbotman** [comment] 2015-03-27 14:56
Indeed, that branch was still under development because I wanted to add some tests before I merged it. But the issue is more important than the test (for which I don't have enough time at the moment) So created PR and will merge it once travis is happy and will merge this minor fix also.

**Comment by tacchino** [comment] 2015-03-27 15:28
Awesome. Thanks for the quick help!

**Comment by sbotman** [comment] 2015-03-27 16:14
@tacchino since I have merge the code, I will close this ticket :)

**Closed as completed by sbotman** 2015-03-27 16:14 UTC
